### ISSUE TITLE
add an option for catkin build

### ISSUE THREAD

**Issue by gokulmaxi** [thibthib18/ros-nvim#3]
It would be nice have an option to  choose between catkin_make and catkin build.

**Comment by thibthib18** [comment]
Hi, thanks for the input, I added the option to set the make program via `catkin_program`, you can check out the [updated doc](https://github.com/thibthib18/ros-nvim#%EF%B8%8F--setup) for usage.

**Comment by dongdongbh** [comment]
@thibthib18 changing `catkin_program` to "catkin build" not work in my case, their is still using catkin_make

**Comment by thibthib18** [comment]
This somehow got lost in a previous refactor. I brought it back in latest master.
Thanks for spotting the issue.
