### ISSUE TITLE
Should I manually source devel/setup.bash before invoking the plugin function?

### ISSUE THREAD

**Issue by qlibp** [thibthib18/ros-nvim#8]
If I don't source the setup.bash file before entering neovim, I could not find any system-wide ROS package, not to mention the self-defined one.
Is the plugin relies on the bash environments?

**Comment by thibthib18** [comment]
This plugin relies on the ROS command line tools (`rostopic`, `rosnode`, etc...). 
To work correctly, those expect various environments to be set properly, which is what sourcing `setup.bash` does.

**Comment by qlibp** [comment]
> This plugin relies on the ROS command line tools (`rostopic`, `rosnode`, etc...).
> To work correctly, those expect various environments to be set properly, which is what sourcing `setup.bash` does.

Is it possible to source within neovim？

**Comment by thibthib18** [comment]
Typically, one would have some `source <your path>/setup.bash`  lines in their `.bashrc`, to avoid having to source those files manually for every shell.
